### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [noisychanneler/intro_to_data_analysis_capstone#5]
(Exceeds Expectations)

Well done on this project! Good job putting together all the tables and figures. Your observations and analysis were very thorough as well, and your presentation slides are efficient in presenting your findings. And great attention to details! I liked how you used different text color and font weight (ie. bold) to highlight key points and results in your slides!

As a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by noisychanneler** [comment]
Thanks for the thorough review!
